retour à EhCache 2.8.2 à cause de : Caused by: java.lang.NoSuchMethodError: net.sf.ehcache.util.ClassLoaderUtil.getStandardClassLoader()Ljava/lang/ClassLoader; 	at org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory.loadResource(AbstractEhcacheRegionFactory.java:202) 	at org.hibernate.cache.ehcache.EhCacheRegionFactory.start(EhCacheRegionFactory.java:89) 	at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:70) 	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:40) 	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:35) 	at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:91)
git-svn-id: svn+ssh://svn.projects.openwide.fr/svnroot/owsi-tools/trunk/owsi-core@3299 d3474844-eb8e-4abc-b058-2b321fed648b