retour à Hibernate 5.0.3
on a des :
java.lang.NoClassDefFoundError: javax/transaction/SystemException
Caused by: java.lang.NoClassDefFoundError:
javax/transaction/SystemException
Caused by: java.lang.ClassNotFoundException:
javax.transaction.SystemException