Revert "Add a specific sort field for GenericEntity.id (named ID_SORT)"
This caused some applications to explode with the following Exception:
org.hibernate.search.exception.SearchException: HSEARCH000262: @NumericField annotation is used on com.foo.MyEntity#id without a matching @Field annotation

This reverts commit a573f63587262929440794858a752791e2c6db5a.